### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by SSSRgo** [wchapman/pippin#6]
Hello, I have some questions of the code of  the GLM. What is the format of the input data ot Model? I have noticed the root is passed to the Model as data, but I cannot run the example.m, because it can not recognize the 'root'. So how can I run the example.m successfully?

Looking forward to your reply.
Thanks!

**Comment by wchapman** [comment]
Hi there,

The expected input is [CMBHOME](https://github.com/hasselmonians/CMBHOME) structure. That repo has a wiki page with some information on how to import from raw data [here](https://github.com/hasselmonians/CMBHOME/wiki/Importing-Data).

**Comment by SSSRgo** [comment]
OK. Thank you so much!
